version: 2
jobs:
  python2.7:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: python run.py deps
      - run: python run.py ci-driver
  python3.9:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: python run.py deps
      - run: python3 run.py ci-driver
workflows:
  version: 2
  arm64:
    jobs:
      - python2.7
      - python3.9
