version: 2
jobs:
  py26:
    macos:
      # macOS 10.12, last version with Python 2.6
      xcode: 9.0.1
    steps:
      - checkout
      - run: /usr/bin/python2.6 run.py deps
      - run: /usr/bin/python2.6 run.py ci
  pypy:
    macos:
      # macOS 10.14.4
      xcode: 10.3.0
    steps:
      - checkout
      - run: curl --location -O https://downloads.python.org/pypy/pypy2.7-v7.3.2-osx64.tar.bz2
      - run: tar xvf pypy2.7-v7.3.2-osx64.tar.bz2
      - run: mv pypy2.7-v7.3.2-osx64 pypy
      - run: xattr -rc pypy
      - run: ./pypy/bin/pypy -m ensurepip
      - run: ./pypy/bin/pypy run.py deps
      - run: ./pypy/bin/pypy run.py ci
workflows:
  version: 2
  python-26:
    jobs:
      - py26
  python-pypy:
    jobs:
      - pypy
